# -*- coding: utf-8 -*-
"""01-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19-D1z11kCQPU9rN73p3UyXjuiz8g-Ve7

# 마켓과 머신러닝

<table align="left"><tr><td>
<a href="https://colab.research.google.com/github/rickiepark/hg-mldl2/blob/main/01-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="코랩에서 실행하기"/></a>
</td></tr></table>

## 생선 분류 문제
"""

#%%

### 도미 데이터 준비하기

bream_length = [25.4, 26.3, 26.5, 29.0, 29.0, 29.7, 29.7, 30.0, 30.0, 30.7, 31.0, 31.0, 31.5, 32.0, 32.0, 32.0, 33.0, 33.0, 33.5, 33.5, 34.0, 34.0, 34.5, 35.0, 35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.5, 38.5, 39.5, 41.0, 41.0]
bream_weight = [242.0, 290.0, 340.0, 363.0, 430.0, 450.0, 500.0, 390.0, 450.0, 500.0, 475.0, 500.0, 500.0, 340.0, 600.0, 600.0, 700.0, 700.0, 610.0, 650.0, 575.0, 685.0, 620.0, 680.0, 700.0, 725.0, 720.0, 714.0, 850.0, 1000.0, 920.0, 955.0, 925.0, 975.0, 950.0]

#%%

import matplotlib.pyplot as plt

plt.scatter(bream_length, bream_weight)
plt.xlabel('length')
plt.ylabel('weight')
plt.show()

#%%

"""### 빙어 데이터 준비하기"""
# 빙어의 길이, 무게
# 14건
smelt_length = [9.8, 10.5, 10.6, 11.0, 11.2, 11.3, 11.8, 11.8, 12.0, 12.2, 12.4, 13.0, 14.3, 15.0]
smelt_weight = [6.7, 7.5, 7.0, 9.7, 9.8, 8.7, 10.0, 9.9, 9.8, 12.2, 13.4, 12.2, 19.7, 19.9]

# 도미와 빙어의 그래프
plt.scatter(bream_length, bream_weight) # 도미 데이터
plt.scatter(smelt_length, smelt_weight) # 빙어 데이터
plt.xlabel('length')
plt.ylabel('weight')
plt.show()

#%%

"""## 첫 번째 머신러닝 프로그램"""

# 도미 데이터와 빙어 데이터 합치기
length = bream_length + smelt_length
weight = bream_weight + smelt_weight

# [l:길이, w:무게]
fish_data = [[l, w] for l, w in zip(length, weight)]
print('도미 데이터의 갯수:', len(bream_length))
print('빙어 데이터의 갯수:', len(smelt_length))
print('도미와 빙어 데이터의 갯수:', len(fish_data))
print(fish_data)

# 타겟(정답) 데이터
# 도미: 1(35개)
# 빙어: 0(14개)
fish_target = [1]*35 + [0]*14
print(fish_target)

#%%

# k-최근접 이웃 알고리즘
from sklearn.neighbors import KNeighborsClassifier

# 객체 생성
kn = KNeighborsClassifier()

# 훈련(training)
# 훈련 데이터: fish_data
# 정답 데이터: fish_target
kn.fit(fish_data, fish_target)

# 평가
kn.score(fish_data, fish_target)

#%%
"""### k-최근접 이웃 알고리즘"""

plt.scatter(bream_length, bream_weight)
plt.scatter(smelt_length, smelt_weight)
plt.scatter(30, 600, marker='^')
plt.xlabel('length')
plt.ylabel('weight')
plt.show()

#%%

# 예측: 훈련 데이터와 같은 형식으로 인자를 전달
# [길이, 무게]
print(kn.predict([[30, 600]])) # [1] 도미
print(kn.predict([[10, 8]]))   # [0] 빙어
print(kn.predict([[11, 9]]))   # [0] 빙어
print(kn.predict([[20, 150]])) # [0] 빙어
print(kn.predict([[20, 200]])) # [1] 도미

#%%

# 여러개를 예측
test = [[30, 600],  # [1] 도미
        [10, 8],    # [0] 빙어
        [11, 9],    # [0] 빙어
        [20, 150],  # [0] 빙어
        [20, 200]]  # [1] 도미

print(kn.predict(test)) # [1 0 0 0 1]

#%%

# 훈련(fit)시 전달받아 메모리에 보관하고 있는 훈련 데이터와 정답 데이터
print(kn._fit_X) # 훈련시 지정한 데이터(X): fish_data
print(kn._y)     # 훈련시 지정한 정답(Ground Truth): fish_target 

#%%

# 이웃의 갯수(n_neighbors)
# n_neighbors=49
# 전체 훈련 데이터 갯수: 49개
kn49 = KNeighborsClassifier(n_neighbors=49)

kn49.fit(fish_data, fish_target)
print(kn49.score(fish_data, fish_target)) # 0.7142857142857143

print(35/49) # 0.7142857142857143

# 모두 도미(1)로 예측
print(kn49.predict(test)) # [1 1 1 1 1]

#%%

"""### 확인 문제"""

kn = KNeighborsClassifier()
kn.fit(fish_data, fish_target)

# 하이퍼파라미터 조정: n_neighbors
for n in range(5, 50): # 이웃의 갯수: 5~49
    # 최근접 이웃 개수 설정
    kn.n_neighbors = n
    
    # 점수 계산: 예측 후에 정답과 비교
    score = kn.score(fish_data, fish_target)
    print(f"[score] n={n}, score={score}")
    
    # 100% 정확도에 미치지 못하는 이웃 개수 출력
    """
    if score < 1.0:
        print(f"[score] n={n}, score={score}")
        break
    """
