# -*- coding: utf-8 -*-
"""ch06_01_huggingface LLM inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trzXv3sY0KLHyCAQCEmvdw5OaNE7zHnA
"""

# transformers와 torch 라이브러리를 임포트합니다.
# transformers는 Hugging Face에서 제공하는 다양한 사전 학습된 모델과 도구를 제공하며,
# torch는 딥러닝을 위한 PyTorch 라이브러리입니다.
import transformers==4.47.1
import torch==2.5.1+cu121

# 사용할 모델의 ID를 설정합니다.
# 여기서는 한국어 Llama 모델인 "MLP-KTLim/llama-3-Korean-Bllossom-8B"를 실습에 사용합니다.
model_id = "MLP-KTLim/llama-3-Korean-Bllossom-8B"

# 텍스트 생성 파이프라인을 설정합니다.
pipeline = transformers.pipeline(
    "text-generation",  # 작업 유형을 'text-generation'으로 설정하여 텍스트 생성 기능을 사용합니다.
    model=model_id,  # 지정한 모델 ID로 모델을 로드합니다.
    model_kwargs={"torch_dtype": torch.bfloat16},  # 모델을 bfloat16 데이터 타입으로 설정하여 메모리 효율을 높입니다.
    device_map="auto",  # 사용 가능한 GPU를 자동으로 할당하여 실행합니다.
)

# 모델을 평가 모드로 전환합니다.
# 평가 모드에서는 훈련 기능이 비활성화되며, 모델이 추론(예측)에 최적화된 상태로 변경됩니다.
pipeline.model.eval()

# AI 어시스턴트가 사용자 질문에 대해 친절하게 답변할 수 있도록
# 대화 형식의 프롬프트를 설정하고, 필요한 종료 조건을 정의하는 과정입니다.
# PROMPT와 instruction을 통해 AI의 역할과 사용자 요청을 설정하고,
# messages 리스트로 대화 흐름을 정의하여 최종적으로 prompt를 생성합니다.
# terminators 리스트는 대화 종료에 사용될 토큰 ID를 지정하여,
# AI가 적절한 시점에 대화를 마칠 수 있도록 합니다.

# AI 어시스턴트의 역할을 정의하는 문구를 PROMPT 변수에 저장합니다.
PROMPT = '''당신은 유능한 AI 어시스턴트 입니다. 사용자의 질문에 대해 친절하게 답변해주세요.'''

# 사용자가 AI에게 요청하는 작업 내용을 instruction 변수에 저장합니다.
instruction = "서울의 유명한 관광 코스를 만들어줄래?"

# messages 리스트를 생성하여 대화의 흐름을 정의합니다.
messages = [
    {"role": "system", "content": f"{PROMPT}"},  # "system" 역할로 AI의 기본 역할을 정의하는 PROMPT를 포함합니다.
    {"role": "user", "content": f"{instruction}"}  # "user" 역할로 사용자가 요청한 instruction을 포함합니다.
]

# 메시지 리스트를 기반으로 대화용 prompt를 생성합니다.
# pipeline.tokenizer.apply_chat_template 함수를 사용하여 messages 리스트를 템플릿 형식에 맞게 변환하고,
# tokenize=False로 설정해 텍스트 그대로 생성에 활용할 수 있도록 합니다.
prompt = pipeline.tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True  # 텍스트 생성을 위한 추가 정보를 포함해 prompt를 구성합니다.
)

print(prompt)

# 대화를 종료하는 데 사용될 토큰 ID들이 포함된 terminators 리스트를 정의합니다.
# 이 리스트는 종료 조건으로 사용되는 특별 토큰(eos_token_id와 <|eot_id|>)을 포함하여 대화가 적절히 종료될 수 있도록 합니다.
terminators = [
    pipeline.tokenizer.eos_token_id,
    pipeline.tokenizer.convert_tokens_to_ids("<|eot_id|>")
]
# outputs 변수에 텍스트 생성 결과를 저장합니다. pipeline 함수는 생성된 텍스트를 반환합니다.
outputs = pipeline(
    prompt,  # 앞서 생성된 prompt를 사용하여 모델이 텍스트를 생성하도록 합니다.
    max_new_tokens=2048,  # 최대 2048개의 새로운 토큰을 생성할 수 있도록 설정합니다.
    eos_token_id=terminators,  # terminators 리스트에 포함된 종료 토큰을 만나면 생성을 중단합니다.
    do_sample=True,  # 샘플링 방식으로 텍스트를 생성하여 결과가 다양하게 나올 수 있게 합니다.
    temperature=0.6,  # 샘플링 확률 분포를 조절하여 모델이 결정적으로 또는 창의적으로 행동하도록 설정합니다.
    top_p=0.9  # 상위 90%에 해당하는 누적 확률의 토큰만을 고려하여 샘플링을 진행합니다.
)

# 생성된 텍스트 출력. prompt 길이 이후의 텍스트만 출력하여 사용자 요청에 대한 응답을 표시합니다.
print(outputs[0]["generated_text"][len(prompt):])

"""# 프롬프트 직접 만들어서 바로 쓰기"""

prompt = "서울에서 갈만한 곳 추천해줘"

outputs = pipeline(
    prompt,
    max_new_tokens=256,
    eos_token_id=terminators,
    do_sample=True,
    temperature=0.6,
    top_p=0.9
)

print(outputs[0]["generated_text"][len(prompt):])

